name: MetricsClassic
on:
  schedule:
    - cron: "0 0 * * *"  # Se actualiza cada día
  workflow_dispatch:       # También puedes ejecutarlo manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.classic.svg
          base: header, repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
